version: '3.8'
services:
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped
    environment:
      - PORT=4004
      - MONGO_URL=mongodb+srv://smart-box-service:3pKAqDxRQjWxceMi@cluster0.4ortpxt.mongodb.net/?retryWrites=true&w=majority
      - INCIDENT_MAIL_HOST=smtp.ethereal.email
      - INCIDENT_MAIL_PORT=587
      - INCIDENT_MAIL_USERNAME
      - INCIDENT_MAIL_PASSWORD
    ports:
      - '4004:4004'
    networks:
      - scoobydoo
  frontend:
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL
      - REACT_APP_FRONTEND_HOST
      - NODE_ENV=production
    build:
      context: ./frontend
      target: dev
      args:
        REACT_APP_BACKEND_URL: https://smart-box.one-calendar.de/api
        REACT_APP_FRONTEND_HOST: https://smart-box.one-calendar.de
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
    ports:
      - '3004:3000'
    networks:
      - scoobydoo
    command: npm run start
volumes:
  mongo:
networks:
  scoobydoo:
    external: true
