version: '3'
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      target: dev
    ports:
      - '4004:4004'
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
